// Code generated by Lorm. DO NOT EDIT.

package test

import (
	json "github.com/bytedance/sonic"

	"github.com/yvvlee/lorm"
)

func (m *Test) New() lorm.Model {
	return new(Test)
}

func (m *Test) LormFieldMap() map[string]any {
	return map[string]any{
		"id":          &m.ID,
		"int":         &m.Int,
		"int_p":       &m.IntP,
		"bool":        &m.Bool,
		"bool_p":      &m.BoolP,
		"str":         &m.Str,
		"str_p":       &m.StrP,
		"timestamp":   &m.Timestamp,
		"timestamp_p": &m.TimestampP,
		"datetime":    &m.Datetime,
		"datetime_p":  &m.DatetimeP,
		"decimal":     &m.Decimal,
		"decimal_p":   &m.DecimalP,
		"int_slice":   &m.IntSlice,
		"int_slice_p": &m.IntSliceP,
		"struct":      &m.Struct,
		"struct_p":    &m.StructP,
	}
}

func (m *Test) LormModelDescriptor() *lorm.ModelDescriptor {
	return _lorm_file_test_model_model_descriptor_map["Test"]
}

func (m *Test) Fields() *Test_Fields {
	return new(Test_Fields)
}

type Test_Fields struct {
	alias string
}

func (f *Test_Fields) WithAlias(alias string) *Test_Fields {
	f.alias = alias
	return f
}
func (f *Test_Fields) ID() string {
	if f.alias == "" {
		return "id"
	}
	return f.alias + ".id"
}
func (f *Test_Fields) Int() string {
	if f.alias == "" {
		return "int"
	}
	return f.alias + ".int"
}
func (f *Test_Fields) IntP() string {
	if f.alias == "" {
		return "int_p"
	}
	return f.alias + ".int_p"
}
func (f *Test_Fields) Bool() string {
	if f.alias == "" {
		return "bool"
	}
	return f.alias + ".bool"
}
func (f *Test_Fields) BoolP() string {
	if f.alias == "" {
		return "bool_p"
	}
	return f.alias + ".bool_p"
}
func (f *Test_Fields) Str() string {
	if f.alias == "" {
		return "str"
	}
	return f.alias + ".str"
}
func (f *Test_Fields) StrP() string {
	if f.alias == "" {
		return "str_p"
	}
	return f.alias + ".str_p"
}
func (f *Test_Fields) Timestamp() string {
	if f.alias == "" {
		return "timestamp"
	}
	return f.alias + ".timestamp"
}
func (f *Test_Fields) TimestampP() string {
	if f.alias == "" {
		return "timestamp_p"
	}
	return f.alias + ".timestamp_p"
}
func (f *Test_Fields) Datetime() string {
	if f.alias == "" {
		return "datetime"
	}
	return f.alias + ".datetime"
}
func (f *Test_Fields) DatetimeP() string {
	if f.alias == "" {
		return "datetime_p"
	}
	return f.alias + ".datetime_p"
}
func (f *Test_Fields) Decimal() string {
	if f.alias == "" {
		return "decimal"
	}
	return f.alias + ".decimal"
}
func (f *Test_Fields) DecimalP() string {
	if f.alias == "" {
		return "decimal_p"
	}
	return f.alias + ".decimal_p"
}
func (f *Test_Fields) IntSlice() string {
	if f.alias == "" {
		return "int_slice"
	}
	return f.alias + ".int_slice"
}
func (f *Test_Fields) IntSliceP() string {
	if f.alias == "" {
		return "int_slice_p"
	}
	return f.alias + ".int_slice_p"
}
func (f *Test_Fields) Struct() string {
	if f.alias == "" {
		return "struct"
	}
	return f.alias + ".struct"
}
func (f *Test_Fields) StructP() string {
	if f.alias == "" {
		return "struct_p"
	}
	return f.alias + ".struct_p"
}

func (f *Test_Fields) All() []string {
	return []string{
		f.ID(),
		f.Int(),
		f.IntP(),
		f.Bool(),
		f.BoolP(),
		f.Str(),
		f.StrP(),
		f.Timestamp(),
		f.TimestampP(),
		f.Datetime(),
		f.DatetimeP(),
		f.Decimal(),
		f.DecimalP(),
		f.IntSlice(),
		f.IntSliceP(),
		f.Struct(),
		f.StructP(),
	}
}

const _lorm_file_test_model_raw = `{"Path":"test/model.go","LormImportAlias":"lorm","Package":"test","Imports":[{"Path":"\"time\"","Alias":""},{"Path":"\"github.com/shopspring/decimal\"","Alias":""},{"Path":"\"github.com/yvvlee/lorm\"","Alias":""}],"Structs":[{"Name":"Test","TableName":"","Fields":[{"Name":"ID","FullName":"ID","DBField":"id","Type":"uint64","Flag":3},{"Name":"Int","FullName":"Int","DBField":"int","Type":"int","Flag":0},{"Name":"IntP","FullName":"IntP","DBField":"int_p","Type":"*int","Flag":0},{"Name":"Bool","FullName":"Bool","DBField":"bool","Type":"bool","Flag":0},{"Name":"BoolP","FullName":"BoolP","DBField":"bool_p","Type":"*bool","Flag":0},{"Name":"Str","FullName":"Str","DBField":"str","Type":"string","Flag":0},{"Name":"StrP","FullName":"StrP","DBField":"str_p","Type":"*string","Flag":0},{"Name":"Timestamp","FullName":"Timestamp","DBField":"timestamp","Type":"time.Time","Flag":0},{"Name":"TimestampP","FullName":"TimestampP","DBField":"timestamp_p","Type":"*time.Time","Flag":0},{"Name":"Datetime","FullName":"Datetime","DBField":"datetime","Type":"time.Time","Flag":0},{"Name":"DatetimeP","FullName":"DatetimeP","DBField":"datetime_p","Type":"*time.Time","Flag":0},{"Name":"Decimal","FullName":"Decimal","DBField":"decimal","Type":"decimal.Decimal","Flag":0},{"Name":"DecimalP","FullName":"DecimalP","DBField":"decimal_p","Type":"*decimal.Decimal","Flag":0},{"Name":"IntSlice","FullName":"IntSlice","DBField":"int_slice","Type":"[]int","Flag":4},{"Name":"IntSliceP","FullName":"IntSliceP","DBField":"int_slice_p","Type":"*[]int","Flag":4},{"Name":"Struct","FullName":"Struct","DBField":"struct","Type":"Sub","Flag":4},{"Name":"StructP","FullName":"StructP","DBField":"struct_p","Type":"*Sub","Flag":4}]}]}`

var _lorm_file_test_model_model_descriptor_map = func() map[string]*lorm.ModelDescriptor {
	var file lorm.FileDescriptor
	_ = json.UnmarshalString(_lorm_file_test_model_raw, &file)
	m := make(map[string]*lorm.ModelDescriptor, len(file.Structs))
	for _, s := range file.Structs {
		m[s.Name] = s
	}
	return m
}()
