// Code generated by Lorm. DO NOT EDIT.

package lorm

import (
	json "github.com/bytedance/sonic"
)

func (m *Test) TableName() string {
	return "test"
}

func (m *Test) New() Model {
	return new(Test)
}

func (m *Test) LormFieldPtr(name string) any {
	switch name {
	case "id":
		return &m.ID
	case "index":
		return &m.Int
	case "int_p":
		return &m.IntP
	case "bool":
		return &m.Bool
	case "bool_p":
		return &m.BoolP
	case "str":
		return &m.Str
	case "str_p":
		return &m.StrP
	case "timestamp":
		return &m.Timestamp
	case "timestamp_p":
		return &m.TimestampP
	case "datetime":
		return &m.Datetime
	case "datetime_p":
		return &m.DatetimeP
	case "decimal":
		return &m.Decimal
	case "decimal_p":
		return &m.DecimalP
	case "int_slice":
		return NewJSONFieldWrapper(&m.IntSlice)
	case "int_slice_p":
		return NewJSONFieldWrapper(&m.IntSliceP)
	case "struct":
		return NewJSONFieldWrapper(&m.Struct)
	case "struct_p":
		return NewJSONFieldWrapper(&m.StructP)
	case "created_at":
		return &m.CreatedAt
	case "updated_at":
		return &m.UpdatedAt
	default:
		return nil
	}
}

func (m *Test) LormScan(row RowScanner) error {
	return row.Scan(
		&m.ID,
		&m.Int,
		&m.IntP,
		&m.Bool,
		&m.BoolP,
		&m.Str,
		&m.StrP,
		&m.Timestamp,
		&m.TimestampP,
		&m.Datetime,
		&m.DatetimeP,
		&m.Decimal,
		&m.DecimalP,
		NewJSONFieldWrapper(&m.IntSlice),
		NewJSONFieldWrapper(&m.IntSliceP),
		NewJSONFieldWrapper(&m.Struct),
		NewJSONFieldWrapper(&m.StructP),
		&m.CreatedAt,
		&m.UpdatedAt,
	)
}

func (m *Test) LormFieldValue(name string) any {
	switch name {
	case "id":
		return m.ID
	case "index":
		return m.Int
	case "int_p":
		if m.IntP == nil {
			return nil
		}
		return m.IntP
	case "bool":
		return m.Bool
	case "bool_p":
		if m.BoolP == nil {
			return nil
		}
		return m.BoolP
	case "str":
		return m.Str
	case "str_p":
		if m.StrP == nil {
			return nil
		}
		return m.StrP
	case "timestamp":
		return m.Timestamp
	case "timestamp_p":
		if m.TimestampP == nil {
			return nil
		}
		return m.TimestampP
	case "datetime":
		return m.Datetime
	case "datetime_p":
		if m.DatetimeP == nil {
			return nil
		}
		return m.DatetimeP
	case "decimal":
		return m.Decimal
	case "decimal_p":
		if m.DecimalP == nil {
			return nil
		}
		return m.DecimalP
	case "int_slice":
		return NewJSONFieldWrapper(&m.IntSlice)
	case "int_slice_p":
		return NewJSONFieldWrapper(&m.IntSliceP)
	case "struct":
		return NewJSONFieldWrapper(&m.Struct)
	case "struct_p":
		return NewJSONFieldWrapper(&m.StructP)
	case "created_at":
		return m.CreatedAt
	case "updated_at":
		return m.UpdatedAt
	default:
		return nil
	}
}

var _lorm_file_test_model_Test_model_descriptor = func() *ModelDescriptor {
	descriptor := _lorm_file_test_model_model_descriptor_map["Test"]
	descriptor.PrimaryKeys = []string{"id"}
	return descriptor
}()

func (m *Test) LormModelDescriptor() *ModelDescriptor {
	return _lorm_file_test_model_Test_model_descriptor
}

func (m *Test) Fields() *Test_Fields {
	return default_Test_Fields
}

var default_Test_Fields = new(Test_Fields)

type Test_Fields struct {
	alias string
}

func (f *Test_Fields) WithAlias(alias string) *Test_Fields {
	o := new(Test_Fields)
	o.alias = alias
	return o
}
func (f *Test_Fields) ID() string {
	if f.alias == "" {
		return "id"
	}
	return f.alias + ".id"
}
func (f *Test_Fields) Int() string {
	if f.alias == "" {
		return "index"
	}
	return f.alias + ".index"
}
func (f *Test_Fields) IntP() string {
	if f.alias == "" {
		return "int_p"
	}
	return f.alias + ".int_p"
}
func (f *Test_Fields) Bool() string {
	if f.alias == "" {
		return "bool"
	}
	return f.alias + ".bool"
}
func (f *Test_Fields) BoolP() string {
	if f.alias == "" {
		return "bool_p"
	}
	return f.alias + ".bool_p"
}
func (f *Test_Fields) Str() string {
	if f.alias == "" {
		return "str"
	}
	return f.alias + ".str"
}
func (f *Test_Fields) StrP() string {
	if f.alias == "" {
		return "str_p"
	}
	return f.alias + ".str_p"
}
func (f *Test_Fields) Timestamp() string {
	if f.alias == "" {
		return "timestamp"
	}
	return f.alias + ".timestamp"
}
func (f *Test_Fields) TimestampP() string {
	if f.alias == "" {
		return "timestamp_p"
	}
	return f.alias + ".timestamp_p"
}
func (f *Test_Fields) Datetime() string {
	if f.alias == "" {
		return "datetime"
	}
	return f.alias + ".datetime"
}
func (f *Test_Fields) DatetimeP() string {
	if f.alias == "" {
		return "datetime_p"
	}
	return f.alias + ".datetime_p"
}
func (f *Test_Fields) Decimal() string {
	if f.alias == "" {
		return "decimal"
	}
	return f.alias + ".decimal"
}
func (f *Test_Fields) DecimalP() string {
	if f.alias == "" {
		return "decimal_p"
	}
	return f.alias + ".decimal_p"
}
func (f *Test_Fields) IntSlice() string {
	if f.alias == "" {
		return "int_slice"
	}
	return f.alias + ".int_slice"
}
func (f *Test_Fields) IntSliceP() string {
	if f.alias == "" {
		return "int_slice_p"
	}
	return f.alias + ".int_slice_p"
}
func (f *Test_Fields) Struct() string {
	if f.alias == "" {
		return "struct"
	}
	return f.alias + ".struct"
}
func (f *Test_Fields) StructP() string {
	if f.alias == "" {
		return "struct_p"
	}
	return f.alias + ".struct_p"
}
func (f *Test_Fields) CreatedAt() string {
	if f.alias == "" {
		return "created_at"
	}
	return f.alias + ".created_at"
}
func (f *Test_Fields) UpdatedAt() string {
	if f.alias == "" {
		return "updated_at"
	}
	return f.alias + ".updated_at"
}

func (f *Test_Fields) All() []string {
	return []string{
		f.ID(),
		f.Int(),
		f.IntP(),
		f.Bool(),
		f.BoolP(),
		f.Str(),
		f.StrP(),
		f.Timestamp(),
		f.TimestampP(),
		f.Datetime(),
		f.DatetimeP(),
		f.Decimal(),
		f.DecimalP(),
		f.IntSlice(),
		f.IntSliceP(),
		f.Struct(),
		f.StructP(),
		f.CreatedAt(),
		f.UpdatedAt(),
	}
}

const _lorm_file_test_model_raw = `{"Path":"test/model.go","LormImportAlias":"lorm","Package":"test","Imports":[{"Path":"\"time\"","Alias":""},{"Path":"\"github.com/shopspring/decimal\"","Alias":""},{"Path":"\"github.com/yvvlee/lorm\"","Alias":""}],"Structs":[{"Name":"Test","TableName":"test","Fields":[{"Name":"ID","FullName":"ID","DBField":"id","Type":"uint64","Flag":3},{"Name":"Int","FullName":"Int","DBField":"index","Type":"int","Flag":0},{"Name":"IntP","FullName":"IntP","DBField":"int_p","Type":"*int","Flag":0},{"Name":"Bool","FullName":"Bool","DBField":"bool","Type":"bool","Flag":0},{"Name":"BoolP","FullName":"BoolP","DBField":"bool_p","Type":"*bool","Flag":0},{"Name":"Str","FullName":"Str","DBField":"str","Type":"string","Flag":0},{"Name":"StrP","FullName":"StrP","DBField":"str_p","Type":"*string","Flag":0},{"Name":"Timestamp","FullName":"Timestamp","DBField":"timestamp","Type":"time.Time","Flag":0},{"Name":"TimestampP","FullName":"TimestampP","DBField":"timestamp_p","Type":"*time.Time","Flag":0},{"Name":"Datetime","FullName":"Datetime","DBField":"datetime","Type":"time.Time","Flag":0},{"Name":"DatetimeP","FullName":"DatetimeP","DBField":"datetime_p","Type":"*time.Time","Flag":0},{"Name":"Decimal","FullName":"Decimal","DBField":"decimal","Type":"decimal.Decimal","Flag":0},{"Name":"DecimalP","FullName":"DecimalP","DBField":"decimal_p","Type":"*decimal.Decimal","Flag":0},{"Name":"IntSlice","FullName":"IntSlice","DBField":"int_slice","Type":"[]int","Flag":4},{"Name":"IntSliceP","FullName":"IntSliceP","DBField":"int_slice_p","Type":"*[]int","Flag":4},{"Name":"Struct","FullName":"Struct","DBField":"struct","Type":"Sub","Flag":4},{"Name":"StructP","FullName":"StructP","DBField":"struct_p","Type":"*Sub","Flag":4},{"Name":"CreatedAt","FullName":"CreatedAt","DBField":"created_at","Type":"time.Time","Flag":8},{"Name":"UpdatedAt","FullName":"UpdatedAt","DBField":"updated_at","Type":"time.Time","Flag":16}]}]}`

var _lorm_file_test_model_model_descriptor_map = func() map[string]*ModelDescriptor {
	var file FileDescriptor
	_ = json.UnmarshalString(_lorm_file_test_model_raw, &file)
	m := make(map[string]*ModelDescriptor, len(file.Structs))
	for _, s := range file.Structs {
		m[s.Name] = s
	}
	return m
}()
