// Code generated by Lorm. DO NOT EDIT.

package main

import (
	json "github.com/bytedance/sonic"

	"github.com/yvvlee/lorm"
)

func (m *User) TableName() string {
	return "users"
}

func (m *User) New() lorm.Model {
	return new(User)
}

func (m *User) LormFieldPtr(name string) any {
	switch name {
	case "id":
		return &m.ID
	case "name":
		return &m.Name
	case "email":
		return &m.Email
	case "age":
		return &m.Age
	case "created_at":
		return &m.CreatedAt
	case "updated_at":
		return &m.UpdatedAt
	default:
		return nil
	}
}

func (m *User) LormScan(row lorm.RowScanner) error {
	return row.Scan(
		&m.ID,
		&m.Name,
		&m.Email,
		&m.Age,
		&m.CreatedAt,
		&m.UpdatedAt,
	)
}

func (m *User) LormFieldValue(name string) any {
	switch name {
	case "id":
		return m.ID
	case "name":
		return m.Name
	case "email":
		return m.Email
	case "age":
		return m.Age
	case "created_at":
		return m.CreatedAt
	case "updated_at":
		return m.UpdatedAt
	default:
		return nil
	}
}

var _lorm_file_model_5b017786_User_insert_columns = []string{
	"id",
	"name",
	"email",
	"age",
	"created_at",
	"updated_at",
}

var _lorm_file_model_5b017786_User_insert_columns_without_auto_increment = []string{
	"name",
	"email",
	"age",
	"created_at",
	"updated_at",
}

func (m *User) LormBeforeInsert(now lorm.HookTime) lorm.InsertPlan {
	if m.CreatedAt.IsZero() {
		m.CreatedAt = now
	}
	if m.UpdatedAt.IsZero() {
		m.UpdatedAt = now
	}

	plan := lorm.InsertPlan{}
	plan.AutoIncrementColumn = "id"
	plan.AutoIncrementZero = m.ID == 0
	if plan.AutoIncrementZero {
		plan.Columns = _lorm_file_model_5b017786_User_insert_columns_without_auto_increment
	} else {
		plan.Columns = _lorm_file_model_5b017786_User_insert_columns
	}
	plan.Values = make([]any, 0, len(plan.Columns))
	if !plan.AutoIncrementZero {
		plan.Values = append(plan.Values, m.ID)
	}
	plan.Values = append(plan.Values, m.Name)
	plan.Values = append(plan.Values, m.Email)
	plan.Values = append(plan.Values, m.Age)
	plan.Values = append(plan.Values, m.CreatedAt)
	plan.Values = append(plan.Values, m.UpdatedAt)
	return plan
}

func (m *User) LormAfterInsert(result lorm.InsertResult) error {
	if !result.HasGeneratedID {
		return nil
	}
	value, err := lorm.ConvertGeneratedSignedID[int64](result.GeneratedID, 64, "User.ID")
	if err != nil {
		return err
	}
	m.ID = value
	return nil
}

func (m *User) LormBeforeUpdate(now lorm.HookTime) (lorm.UpdatePlan, error) {
	plan := lorm.UpdatePlan{
		Set:       make([]lorm.ColumnValue, 0, 6),
		Where:     make([]lorm.ColumnValue, 0),
		Increment: make([]string, 0, 1),
	}
	plan.PrimaryKeyCount++
	plan.Where = append(plan.Where, lorm.ColumnValue{Column: "id", Value: m.ID})
	plan.Set = append(plan.Set, lorm.ColumnValue{Column: "name", Value: m.Name})
	plan.Set = append(plan.Set, lorm.ColumnValue{Column: "email", Value: m.Email})
	plan.Set = append(plan.Set, lorm.ColumnValue{Column: "age", Value: m.Age})
	plan.Set = append(plan.Set, lorm.ColumnValue{Column: "updated_at", Value: now})
	return plan, nil
}

func (m *User) LormAfterUpdate(now lorm.HookTime, rowsAffected int64) {
	if rowsAffected <= 0 {
		return
	}
	{
		m.UpdatedAt = now
	}
}

var _lorm_file_model_5b017786_User_model_descriptor = _lorm_file_model_5b017786_model_descriptor_map["User"]

func (m *User) LormModelDescriptor() *lorm.ModelDescriptor {
	return _lorm_file_model_5b017786_User_model_descriptor
}

func (m *User) Fields() *User_Fields {
	return default_User_Fields
}

var default_User_Fields = new(User_Fields)

type User_Fields struct {
	alias string
}

func (f *User_Fields) WithAlias(alias string) *User_Fields {
	o := new(User_Fields)
	o.alias = alias
	return o
}
func (f *User_Fields) ID() string {
	if f.alias == "" {
		return "id"
	}
	return f.alias + ".id"
}
func (f *User_Fields) Name() string {
	if f.alias == "" {
		return "name"
	}
	return f.alias + ".name"
}
func (f *User_Fields) Email() string {
	if f.alias == "" {
		return "email"
	}
	return f.alias + ".email"
}
func (f *User_Fields) Age() string {
	if f.alias == "" {
		return "age"
	}
	return f.alias + ".age"
}
func (f *User_Fields) CreatedAt() string {
	if f.alias == "" {
		return "created_at"
	}
	return f.alias + ".created_at"
}
func (f *User_Fields) UpdatedAt() string {
	if f.alias == "" {
		return "updated_at"
	}
	return f.alias + ".updated_at"
}

func (f *User_Fields) All() []string {
	return []string{
		f.ID(),
		f.Name(),
		f.Email(),
		f.Age(),
		f.CreatedAt(),
		f.UpdatedAt(),
	}
}

const _lorm_file_model_5b017786_raw = `{"Path":"model.go","LormImportAlias":"lorm","Package":"main","Imports":[{"Path":"\"time\"","Alias":""},{"Path":"\"github.com/yvvlee/lorm\"","Alias":""}],"Structs":[{"Name":"User","TableName":"users","Fields":[{"Name":"ID","FullName":"ID","DBField":"id","Type":"int64","Flag":3},{"Name":"Name","FullName":"Name","DBField":"name","Type":"string","Flag":0},{"Name":"Email","FullName":"Email","DBField":"email","Type":"string","Flag":0},{"Name":"Age","FullName":"Age","DBField":"age","Type":"int","Flag":0},{"Name":"CreatedAt","FullName":"CreatedAt","DBField":"created_at","Type":"time.Time","Flag":8},{"Name":"UpdatedAt","FullName":"UpdatedAt","DBField":"updated_at","Type":"time.Time","Flag":16}],"PrimaryKeys":["id"]}]}`

var _lorm_file_model_5b017786_model_descriptor_map = func() map[string]*lorm.ModelDescriptor {
	var file lorm.FileDescriptor
	_ = json.UnmarshalString(_lorm_file_model_5b017786_raw, &file)
	m := make(map[string]*lorm.ModelDescriptor, len(file.Structs))
	for _, s := range file.Structs {
		m[s.Name] = s
	}
	return m
}()
