// Code generated by Lorm. DO NOT EDIT.

package main

import (
	json "github.com/bytedance/sonic"

	"github.com/yvvlee/lorm"
)

func (m *User) TableName() string {
	return "users"
}

func (m *User) New() lorm.Model {
	return new(User)
}

func (m *User) LormFieldPtr(name string) any {
	switch name {
	case "id":
		return &m.ID
	case "name":
		return &m.Name
	case "email":
		return &m.Email
	case "created_at":
		return &m.CreatedAt
	case "updated_at":
		return &m.UpdatedAt
	default:
		return nil
	}
}

func (m *User) LormFieldValue(name string) any {
	switch name {
	case "id":
		return m.ID
	case "name":
		return m.Name
	case "email":
		return m.Email
	case "created_at":
		return m.CreatedAt
	case "updated_at":
		return m.UpdatedAt
	default:
		return nil
	}
}

func (m *User) LormModelDescriptor() *lorm.ModelDescriptor {
	return _lorm_file_model_model_descriptor_map["User"]
}

func (m *User) Fields() *User_Fields {
	return default_User_Fields
}

var default_User_Fields = new(User_Fields)

type User_Fields struct {
	alias string
}

func (f *User_Fields) WithAlias(alias string) *User_Fields {
	o := new(User_Fields)
	o.alias = alias
	return o
}
func (f *User_Fields) ID() string {
	if f.alias == "" {
		return "id"
	}
	return f.alias + ".id"
}
func (f *User_Fields) Name() string {
	if f.alias == "" {
		return "name"
	}
	return f.alias + ".name"
}
func (f *User_Fields) Email() string {
	if f.alias == "" {
		return "email"
	}
	return f.alias + ".email"
}
func (f *User_Fields) CreatedAt() string {
	if f.alias == "" {
		return "created_at"
	}
	return f.alias + ".created_at"
}
func (f *User_Fields) UpdatedAt() string {
	if f.alias == "" {
		return "updated_at"
	}
	return f.alias + ".updated_at"
}

func (f *User_Fields) All() []string {
	return []string{
		f.ID(),
		f.Name(),
		f.Email(),
		f.CreatedAt(),
		f.UpdatedAt(),
	}
}

const _lorm_file_model_raw = `{"Path":"model.go","LormImportAlias":"lorm","Package":"main","Imports":[{"Path":"\"time\"","Alias":""},{"Path":"\"github.com/yvvlee/lorm\"","Alias":""}],"Structs":[{"Name":"User","TableName":"users","Fields":[{"Name":"ID","FullName":"ID","DBField":"id","Type":"int64","Flag":3},{"Name":"Name","FullName":"Name","DBField":"name","Type":"string","Flag":0},{"Name":"Email","FullName":"Email","DBField":"email","Type":"string","Flag":0},{"Name":"CreatedAt","FullName":"CreatedAt","DBField":"created_at","Type":"time.Time","Flag":8},{"Name":"UpdatedAt","FullName":"UpdatedAt","DBField":"updated_at","Type":"time.Time","Flag":16}]}]}`

var _lorm_file_model_model_descriptor_map = func() map[string]*lorm.ModelDescriptor {
	var file lorm.FileDescriptor
	_ = json.UnmarshalString(_lorm_file_model_raw, &file)
	m := make(map[string]*lorm.ModelDescriptor, len(file.Structs))
	for _, s := range file.Structs {
		m[s.Name] = s
	}
	return m
}()
