// Code generated by Lorm. DO NOT EDIT.

package testdata

import (
	json "github.com/bytedance/sonic"

	"github.com/yvvlee/lorm"
)

func (m *User) TableName() string {
	return "users"
}

func (m *User) New() lorm.Model {
	return new(User)
}

func (m *User) LormFieldMap() map[string]any {
	return map[string]any{
		"id":         &m.ID,
		"name":       &m.Name,
		"age":        &m.Age,
		"created_at": &m.CreatedAt,
		"updated_at": &m.UpdatedAt,
	}
}

func (m *User) LormModelDescriptor() *lorm.ModelDescriptor {
	return _lorm_file_testdata_user_model_descriptor_map["User"]
}

func (m *User) Fields() *User_Fields {
	return new(User_Fields)
}

type User_Fields struct {
	alias string
}

func (f *User_Fields) WithAlias(alias string) *User_Fields {
	f.alias = alias
	return f
}
func (f *User_Fields) ID() string {
	if f.alias == "" {
		return "id"
	}
	return f.alias + ".id"
}
func (f *User_Fields) Name() string {
	if f.alias == "" {
		return "name"
	}
	return f.alias + ".name"
}
func (f *User_Fields) Age() string {
	if f.alias == "" {
		return "age"
	}
	return f.alias + ".age"
}
func (f *User_Fields) CreatedAt() string {
	if f.alias == "" {
		return "created_at"
	}
	return f.alias + ".created_at"
}
func (f *User_Fields) UpdatedAt() string {
	if f.alias == "" {
		return "updated_at"
	}
	return f.alias + ".updated_at"
}

func (f *User_Fields) All() []string {
	return []string{
		f.ID(),
		f.Name(),
		f.Age(),
		f.CreatedAt(),
		f.UpdatedAt(),
	}
}

const _lorm_file_testdata_user_raw = `{"Path":"testdata/user.go","LormImportAlias":"lorm","Package":"testdata","Imports":[{"Path":"\"time\"","Alias":""},{"Path":"\"github.com/yvvlee/lorm\"","Alias":""}],"Structs":[{"Name":"User","TableName":"users","Fields":[{"Name":"ID","FullName":"ID","DBField":"id","Type":"int","Flag":3},{"Name":"Name","FullName":"Name","DBField":"name","Type":"string","Flag":0},{"Name":"Age","FullName":"Age","DBField":"age","Type":"int","Flag":0},{"Name":"CreatedAt","FullName":"CreatedAt","DBField":"created_at","Type":"time.Time","Flag":8},{"Name":"UpdatedAt","FullName":"UpdatedAt","DBField":"updated_at","Type":"time.Time","Flag":16}]}]}`

var _lorm_file_testdata_user_model_descriptor_map = func() map[string]*lorm.ModelDescriptor {
	var file lorm.FileDescriptor
	_ = json.UnmarshalString(_lorm_file_testdata_user_raw, &file)
	m := make(map[string]*lorm.ModelDescriptor, len(file.Structs))
	for _, s := range file.Structs {
		m[s.Name] = s
	}
	return m
}()
