// Code generated by Lorm. DO NOT EDIT.

package testdata

import (
	json "github.com/bytedance/sonic"

	"github.com/yvvlee/lorm"
)

func (m *UserAddress) New() lorm.Model {
	return new(UserAddress)
}

func (m *UserAddress) LormFieldMap() map[string]any {
	return map[string]any{
		"id":             &m.ID,
		"int64_alias":    &m.Int64Alias,
		"strings":        &m.Strings,
		"addr_address":   &m.Address.Address,
		"addr_post_code": &m.Address.PostCode,
	}
}

func (m *UserAddress) LormModelDescriptor() *lorm.ModelDescriptor {
	return _lorm_file_testdata_user_address_model_descriptor_map["UserAddress"]
}

func (m *UserAddress) Fields() *UserAddress_Fields {
	return new(UserAddress_Fields)
}

type UserAddress_Fields struct {
	alias string
}

func (f *UserAddress_Fields) WithAlias(alias string) *UserAddress_Fields {
	f.alias = alias
	return f
}
func (f *UserAddress_Fields) ID() string {
	if f.alias == "" {
		return "id"
	}
	return f.alias + ".id"
}
func (f *UserAddress_Fields) Int64Alias() string {
	if f.alias == "" {
		return "int64_alias"
	}
	return f.alias + ".int64_alias"
}
func (f *UserAddress_Fields) Strings() string {
	if f.alias == "" {
		return "strings"
	}
	return f.alias + ".strings"
}
func (f *UserAddress_Fields) Address() string {
	if f.alias == "" {
		return "addr_address"
	}
	return f.alias + ".addr_address"
}
func (f *UserAddress_Fields) PostCode() string {
	if f.alias == "" {
		return "addr_post_code"
	}
	return f.alias + ".addr_post_code"
}

func (f *UserAddress_Fields) All() []string {
	return []string{
		f.ID(),
		f.Int64Alias(),
		f.Strings(),
		f.Address(),
		f.PostCode(),
	}
}

const _lorm_file_testdata_user_address_raw = `{"Path":"testdata/user_address.go","LormImportAlias":"lorm","Package":"testdata","Imports":[{"Path":"\"github.com/yvvlee/lorm\"","Alias":""}],"Structs":[{"Name":"UserAddress","TableName":"","Fields":[{"Name":"ID","FullName":"ID","DBField":"id","Type":"int","Flag":3},{"Name":"Int64Alias","FullName":"Int64Alias","DBField":"int64_alias","Type":"Int64Alias","Flag":0},{"Name":"Strings","FullName":"Strings","DBField":"strings","Type":"Strings","Flag":4},{"Name":"Address","FullName":"Address.Address","DBField":"addr_address","Type":"string","Flag":0},{"Name":"PostCode","FullName":"Address.PostCode","DBField":"addr_post_code","Type":"string","Flag":0}]}]}`

var _lorm_file_testdata_user_address_model_descriptor_map = func() map[string]*lorm.ModelDescriptor {
	var file lorm.FileDescriptor
	_ = json.UnmarshalString(_lorm_file_testdata_user_address_raw, &file)
	m := make(map[string]*lorm.ModelDescriptor, len(file.Structs))
	for _, s := range file.Structs {
		m[s.Name] = s
	}
	return m
}()
