// Code generated by Lorm. DO NOT EDIT.

package main

import (
	json "github.com/bytedance/sonic"

	"github.com/yvvlee/lorm"
)

func (m *Post) TableName() string {
	return "posts"
}

func (m *Post) New() lorm.Model {
	return new(Post)
}

func (m *Post) LormFieldPtr(name string) any {
	switch name {
	case "id":
		return &m.ID
	case "title":
		return &m.Title
	case "category":
		return &m.Category
	case "created_at":
		return &m.CreatedAt
	case "updated_at":
		return &m.UpdatedAt
	default:
		return nil
	}
}

func (m *Post) LormFieldValue(name string) any {
	switch name {
	case "id":
		return m.ID
	case "title":
		return m.Title
	case "category":
		return m.Category
	case "created_at":
		return m.CreatedAt
	case "updated_at":
		return m.UpdatedAt
	default:
		return nil
	}
}

func (m *Post) LormModelDescriptor() *lorm.ModelDescriptor {
	return _lorm_file_model_model_descriptor_map["Post"]
}

func (m *Post) Fields() *Post_Fields {
	return default_Post_Fields
}

var default_Post_Fields = new(Post_Fields)

type Post_Fields struct {
	alias string
}

func (f *Post_Fields) WithAlias(alias string) *Post_Fields {
	o := new(Post_Fields)
	o.alias = alias
	return o
}
func (f *Post_Fields) ID() string {
	if f.alias == "" {
		return "id"
	}
	return f.alias + ".id"
}
func (f *Post_Fields) Title() string {
	if f.alias == "" {
		return "title"
	}
	return f.alias + ".title"
}
func (f *Post_Fields) Category() string {
	if f.alias == "" {
		return "category"
	}
	return f.alias + ".category"
}
func (f *Post_Fields) CreatedAt() string {
	if f.alias == "" {
		return "created_at"
	}
	return f.alias + ".created_at"
}
func (f *Post_Fields) UpdatedAt() string {
	if f.alias == "" {
		return "updated_at"
	}
	return f.alias + ".updated_at"
}

func (f *Post_Fields) All() []string {
	return []string{
		f.ID(),
		f.Title(),
		f.Category(),
		f.CreatedAt(),
		f.UpdatedAt(),
	}
}

const _lorm_file_model_raw = `{"Path":"model.go","LormImportAlias":"lorm","Package":"main","Imports":[{"Path":"\"time\"","Alias":""},{"Path":"\"github.com/yvvlee/lorm\"","Alias":""}],"Structs":[{"Name":"Post","TableName":"posts","Fields":[{"Name":"ID","FullName":"ID","DBField":"id","Type":"int64","Flag":3},{"Name":"Title","FullName":"Title","DBField":"title","Type":"string","Flag":0},{"Name":"Category","FullName":"Category","DBField":"category","Type":"string","Flag":0},{"Name":"CreatedAt","FullName":"CreatedAt","DBField":"created_at","Type":"time.Time","Flag":8},{"Name":"UpdatedAt","FullName":"UpdatedAt","DBField":"updated_at","Type":"time.Time","Flag":16}]}]}`

var _lorm_file_model_model_descriptor_map = func() map[string]*lorm.ModelDescriptor {
	var file lorm.FileDescriptor
	_ = json.UnmarshalString(_lorm_file_model_raw, &file)
	m := make(map[string]*lorm.ModelDescriptor, len(file.Structs))
	for _, s := range file.Structs {
		m[s.Name] = s
	}
	return m
}()
