// Code generated by Lorm. DO NOT EDIT.

package main

import (
	json "github.com/bytedance/sonic"

	"github.com/yvvlee/lorm"
)

func (m *Product) TableName() string {
	return "products"
}

func (m *Product) New() lorm.Model {
	return new(Product)
}

func (m *Product) LormFieldPtr(name string) any {
	switch name {
	case "id":
		return &m.ID
	case "name":
		return &m.Name
	case "category":
		return &m.Category
	case "price":
		return &m.Price
	case "status":
		return &m.Status
	case "created_at":
		return &m.CreatedAt
	case "updated_at":
		return &m.UpdatedAt
	default:
		return nil
	}
}

func (m *Product) LormFieldValue(name string) any {
	switch name {
	case "id":
		return m.ID
	case "name":
		return m.Name
	case "category":
		return m.Category
	case "price":
		return m.Price
	case "status":
		return m.Status
	case "created_at":
		return m.CreatedAt
	case "updated_at":
		return m.UpdatedAt
	default:
		return nil
	}
}

func (m *Product) LormModelDescriptor() *lorm.ModelDescriptor {
	return _lorm_file_model_model_descriptor_map["Product"]
}

func (m *Product) Fields() *Product_Fields {
	return default_Product_Fields
}

var default_Product_Fields = new(Product_Fields)

type Product_Fields struct {
	alias string
}

func (f *Product_Fields) WithAlias(alias string) *Product_Fields {
	o := new(Product_Fields)
	o.alias = alias
	return o
}
func (f *Product_Fields) ID() string {
	if f.alias == "" {
		return "id"
	}
	return f.alias + ".id"
}
func (f *Product_Fields) Name() string {
	if f.alias == "" {
		return "name"
	}
	return f.alias + ".name"
}
func (f *Product_Fields) Category() string {
	if f.alias == "" {
		return "category"
	}
	return f.alias + ".category"
}
func (f *Product_Fields) Price() string {
	if f.alias == "" {
		return "price"
	}
	return f.alias + ".price"
}
func (f *Product_Fields) Status() string {
	if f.alias == "" {
		return "status"
	}
	return f.alias + ".status"
}
func (f *Product_Fields) CreatedAt() string {
	if f.alias == "" {
		return "created_at"
	}
	return f.alias + ".created_at"
}
func (f *Product_Fields) UpdatedAt() string {
	if f.alias == "" {
		return "updated_at"
	}
	return f.alias + ".updated_at"
}

func (f *Product_Fields) All() []string {
	return []string{
		f.ID(),
		f.Name(),
		f.Category(),
		f.Price(),
		f.Status(),
		f.CreatedAt(),
		f.UpdatedAt(),
	}
}

const _lorm_file_model_raw = `{"Path":"model.go","LormImportAlias":"lorm","Package":"main","Imports":[{"Path":"\"time\"","Alias":""},{"Path":"\"github.com/yvvlee/lorm\"","Alias":""}],"Structs":[{"Name":"Product","TableName":"products","Fields":[{"Name":"ID","FullName":"ID","DBField":"id","Type":"int64","Flag":3},{"Name":"Name","FullName":"Name","DBField":"name","Type":"string","Flag":0},{"Name":"Category","FullName":"Category","DBField":"category","Type":"string","Flag":0},{"Name":"Price","FullName":"Price","DBField":"price","Type":"int64","Flag":0},{"Name":"Status","FullName":"Status","DBField":"status","Type":"string","Flag":0},{"Name":"CreatedAt","FullName":"CreatedAt","DBField":"created_at","Type":"time.Time","Flag":8},{"Name":"UpdatedAt","FullName":"UpdatedAt","DBField":"updated_at","Type":"time.Time","Flag":16}]}]}`

var _lorm_file_model_model_descriptor_map = func() map[string]*lorm.ModelDescriptor {
	var file lorm.FileDescriptor
	_ = json.UnmarshalString(_lorm_file_model_raw, &file)
	m := make(map[string]*lorm.ModelDescriptor, len(file.Structs))
	for _, s := range file.Structs {
		m[s.Name] = s
	}
	return m
}()
