// Code generated by Lorm. DO NOT EDIT.

package main

import (
	json "github.com/bytedance/sonic"

	"github.com/yvvlee/lorm"
)

func (m *UserProfile) TableName() string {
	return "user_profiles"
}

func (m *UserProfile) New() lorm.Model {
	return new(UserProfile)
}

func (m *UserProfile) LormFieldPtr(name string) any {
	switch name {
	case "id":
		return &m.ID
	case "name":
		return &m.Name
	case "tags":
		return lorm.NewJSONFieldWrapper(&m.Tags)
	case "preferences":
		return lorm.NewJSONFieldWrapper(&m.Preferences)
	case "created_at":
		return &m.CreatedAt
	case "updated_at":
		return &m.UpdatedAt
	default:
		return nil
	}
}

func (m *UserProfile) LormFieldValue(name string) any {
	switch name {
	case "id":
		return m.ID
	case "name":
		return m.Name
	case "tags":
		return lorm.NewJSONFieldWrapper(&m.Tags)
	case "preferences":
		return lorm.NewJSONFieldWrapper(&m.Preferences)
	case "created_at":
		return m.CreatedAt
	case "updated_at":
		return m.UpdatedAt
	default:
		return nil
	}
}

func (m *UserProfile) LormModelDescriptor() *lorm.ModelDescriptor {
	return _lorm_file_model_model_descriptor_map["UserProfile"]
}

func (m *UserProfile) Fields() *UserProfile_Fields {
	return default_UserProfile_Fields
}

var default_UserProfile_Fields = new(UserProfile_Fields)

type UserProfile_Fields struct {
	alias string
}

func (f *UserProfile_Fields) WithAlias(alias string) *UserProfile_Fields {
	o := new(UserProfile_Fields)
	o.alias = alias
	return o
}
func (f *UserProfile_Fields) ID() string {
	if f.alias == "" {
		return "id"
	}
	return f.alias + ".id"
}
func (f *UserProfile_Fields) Name() string {
	if f.alias == "" {
		return "name"
	}
	return f.alias + ".name"
}
func (f *UserProfile_Fields) Tags() string {
	if f.alias == "" {
		return "tags"
	}
	return f.alias + ".tags"
}
func (f *UserProfile_Fields) Preferences() string {
	if f.alias == "" {
		return "preferences"
	}
	return f.alias + ".preferences"
}
func (f *UserProfile_Fields) CreatedAt() string {
	if f.alias == "" {
		return "created_at"
	}
	return f.alias + ".created_at"
}
func (f *UserProfile_Fields) UpdatedAt() string {
	if f.alias == "" {
		return "updated_at"
	}
	return f.alias + ".updated_at"
}

func (f *UserProfile_Fields) All() []string {
	return []string{
		f.ID(),
		f.Name(),
		f.Tags(),
		f.Preferences(),
		f.CreatedAt(),
		f.UpdatedAt(),
	}
}

const _lorm_file_model_raw = `{"Path":"model.go","LormImportAlias":"lorm","Package":"main","Imports":[{"Path":"\"time\"","Alias":""},{"Path":"\"github.com/yvvlee/lorm\"","Alias":""}],"Structs":[{"Name":"UserProfile","TableName":"user_profiles","Fields":[{"Name":"ID","FullName":"ID","DBField":"id","Type":"int64","Flag":3},{"Name":"Name","FullName":"Name","DBField":"name","Type":"string","Flag":0},{"Name":"Tags","FullName":"Tags","DBField":"tags","Type":"[]string","Flag":4},{"Name":"Preferences","FullName":"Preferences","DBField":"preferences","Type":"Preferences","Flag":4},{"Name":"CreatedAt","FullName":"CreatedAt","DBField":"created_at","Type":"time.Time","Flag":8},{"Name":"UpdatedAt","FullName":"UpdatedAt","DBField":"updated_at","Type":"time.Time","Flag":16}]}]}`

var _lorm_file_model_model_descriptor_map = func() map[string]*lorm.ModelDescriptor {
	var file lorm.FileDescriptor
	_ = json.UnmarshalString(_lorm_file_model_raw, &file)
	m := make(map[string]*lorm.ModelDescriptor, len(file.Structs))
	for _, s := range file.Structs {
		m[s.Name] = s
	}
	return m
}()
