// Code generated by Lorm. DO NOT EDIT.

package main

import (
	json "github.com/bytedance/sonic"

	"github.com/yvvlee/lorm"
)

func (m *UserProfile) TableName() string {
	return "user_profiles"
}

func (m *UserProfile) New() lorm.Model {
	return new(UserProfile)
}

func (m *UserProfile) LormFieldPtr(name string) any {
	switch name {
	case "id":
		return &m.ID
	case "name":
		return &m.Name
	case "tags":
		return lorm.NewJSONFieldWrapper(&m.Tags)
	case "preferences":
		return lorm.NewJSONFieldWrapper(&m.Preferences)
	case "created_at":
		return &m.CreatedAt
	case "updated_at":
		return &m.UpdatedAt
	default:
		return nil
	}
}

func (m *UserProfile) LormScan(row lorm.RowScanner) error {
	return row.Scan(
		&m.ID,
		&m.Name,
		lorm.NewJSONFieldWrapper(&m.Tags),
		lorm.NewJSONFieldWrapper(&m.Preferences),
		&m.CreatedAt,
		&m.UpdatedAt,
	)
}

func (m *UserProfile) LormFieldValue(name string) any {
	switch name {
	case "id":
		return m.ID
	case "name":
		return m.Name
	case "tags":
		return lorm.NewJSONFieldWrapper(&m.Tags)
	case "preferences":
		return lorm.NewJSONFieldWrapper(&m.Preferences)
	case "created_at":
		return m.CreatedAt
	case "updated_at":
		return m.UpdatedAt
	default:
		return nil
	}
}

var _lorm_file_model_5b017786_UserProfile_insert_columns = []string{
	"id",
	"name",
	"tags",
	"preferences",
	"created_at",
	"updated_at",
}

var _lorm_file_model_5b017786_UserProfile_insert_columns_without_auto_increment = []string{
	"name",
	"tags",
	"preferences",
	"created_at",
	"updated_at",
}

func (m *UserProfile) LormBeforeInsert(now lorm.HookTime) lorm.InsertPlan {
	if m.CreatedAt.IsZero() {
		m.CreatedAt = now
	}
	if m.UpdatedAt.IsZero() {
		m.UpdatedAt = now
	}

	plan := lorm.InsertPlan{}
	plan.AutoIncrementColumn = "id"
	plan.AutoIncrementZero = m.ID == 0
	if plan.AutoIncrementZero {
		plan.Columns = _lorm_file_model_5b017786_UserProfile_insert_columns_without_auto_increment
	} else {
		plan.Columns = _lorm_file_model_5b017786_UserProfile_insert_columns
	}
	plan.Values = make([]any, 0, len(plan.Columns))
	if !plan.AutoIncrementZero {
		plan.Values = append(plan.Values, m.ID)
	}
	plan.Values = append(plan.Values, m.Name)
	plan.Values = append(plan.Values, lorm.NewJSONFieldWrapper(&m.Tags))
	plan.Values = append(plan.Values, lorm.NewJSONFieldWrapper(&m.Preferences))
	plan.Values = append(plan.Values, m.CreatedAt)
	plan.Values = append(plan.Values, m.UpdatedAt)
	return plan
}

func (m *UserProfile) LormAfterInsert(result lorm.InsertResult) error {
	if !result.HasGeneratedID {
		return nil
	}
	value, err := lorm.ConvertGeneratedSignedID[int64](result.GeneratedID, 64, "UserProfile.ID")
	if err != nil {
		return err
	}
	m.ID = value
	return nil
}

func (m *UserProfile) LormBeforeUpdate(now lorm.HookTime) (lorm.UpdatePlan, error) {
	plan := lorm.UpdatePlan{
		Set:       make([]lorm.ColumnValue, 0, 6),
		Where:     make([]lorm.ColumnValue, 0),
		Increment: make([]string, 0, 1),
	}
	plan.PrimaryKeyCount++
	plan.Where = append(plan.Where, lorm.ColumnValue{Column: "id", Value: m.ID})
	plan.Set = append(plan.Set, lorm.ColumnValue{Column: "name", Value: m.Name})
	plan.Set = append(plan.Set, lorm.ColumnValue{Column: "tags", Value: lorm.NewJSONFieldWrapper(&m.Tags)})
	plan.Set = append(plan.Set, lorm.ColumnValue{Column: "preferences", Value: lorm.NewJSONFieldWrapper(&m.Preferences)})
	plan.Set = append(plan.Set, lorm.ColumnValue{Column: "updated_at", Value: now})
	return plan, nil
}

func (m *UserProfile) LormAfterUpdate(now lorm.HookTime, rowsAffected int64) {
	if rowsAffected <= 0 {
		return
	}
	{
		m.UpdatedAt = now
	}
}

var _lorm_file_model_5b017786_UserProfile_model_descriptor = _lorm_file_model_5b017786_model_descriptor_map["UserProfile"]

func (m *UserProfile) LormModelDescriptor() *lorm.ModelDescriptor {
	return _lorm_file_model_5b017786_UserProfile_model_descriptor
}

func (m *UserProfile) LormCols() *UserProfile_Fields {
	return default_UserProfile_Fields
}

var default_UserProfile_Fields = new(UserProfile_Fields)

type UserProfile_Fields struct {
	alias string
}

func (f *UserProfile_Fields) WithAlias(alias string) *UserProfile_Fields {
	o := new(UserProfile_Fields)
	o.alias = alias
	return o
}
func (f *UserProfile_Fields) ID() string {
	if f.alias == "" {
		return "id"
	}
	return f.alias + ".id"
}
func (f *UserProfile_Fields) Name() string {
	if f.alias == "" {
		return "name"
	}
	return f.alias + ".name"
}
func (f *UserProfile_Fields) Tags() string {
	if f.alias == "" {
		return "tags"
	}
	return f.alias + ".tags"
}
func (f *UserProfile_Fields) Preferences() string {
	if f.alias == "" {
		return "preferences"
	}
	return f.alias + ".preferences"
}
func (f *UserProfile_Fields) CreatedAt() string {
	if f.alias == "" {
		return "created_at"
	}
	return f.alias + ".created_at"
}
func (f *UserProfile_Fields) UpdatedAt() string {
	if f.alias == "" {
		return "updated_at"
	}
	return f.alias + ".updated_at"
}

func (f *UserProfile_Fields) All() []string {
	return []string{
		f.ID(),
		f.Name(),
		f.Tags(),
		f.Preferences(),
		f.CreatedAt(),
		f.UpdatedAt(),
	}
}

const _lorm_file_model_5b017786_raw = `{"Path":"model.go","LormImportAlias":"lorm","Package":"main","Imports":[{"Path":"\"time\"","Alias":""},{"Path":"\"github.com/yvvlee/lorm\"","Alias":""}],"Structs":[{"Name":"UserProfile","TableName":"user_profiles","Fields":[{"Name":"ID","FullName":"ID","DBField":"id","Type":"int64","Flag":3},{"Name":"Name","FullName":"Name","DBField":"name","Type":"string","Flag":0},{"Name":"Tags","FullName":"Tags","DBField":"tags","Type":"[]string","Flag":4},{"Name":"Preferences","FullName":"Preferences","DBField":"preferences","Type":"Preferences","Flag":4},{"Name":"CreatedAt","FullName":"CreatedAt","DBField":"created_at","Type":"time.Time","Flag":8},{"Name":"UpdatedAt","FullName":"UpdatedAt","DBField":"updated_at","Type":"time.Time","Flag":16}],"PrimaryKeys":["id"]}]}`

var _lorm_file_model_5b017786_model_descriptor_map = func() map[string]*lorm.ModelDescriptor {
	var file lorm.FileDescriptor
	_ = json.UnmarshalString(_lorm_file_model_5b017786_raw, &file)
	m := make(map[string]*lorm.ModelDescriptor, len(file.Structs))
	for _, s := range file.Structs {
		m[s.Name] = s
	}
	return m
}()
