// Code generated by Lorm. DO NOT EDIT.

package main

import (
	json "github.com/bytedance/sonic"

	"github.com/yvvlee/lorm"
)

func (m *Report) TableName() string {
	return "reports"
}

func (m *Report) New() lorm.Model {
	return new(Report)
}

func (m *Report) LormFieldPtr(name string) any {
	switch name {
	case "id":
		return &m.ID
	case "title":
		return &m.Title
	case "scores":
		return &m.Scores
	case "created_at":
		return &m.CreatedAt
	case "updated_at":
		return &m.UpdatedAt
	default:
		return nil
	}
}

func (m *Report) LormScan(row lorm.RowScanner) error {
	return row.Scan(
		&m.ID,
		&m.Title,
		&m.Scores,
		&m.CreatedAt,
		&m.UpdatedAt,
	)
}

func (m *Report) LormFieldValue(name string) any {
	switch name {
	case "id":
		return m.ID
	case "title":
		return m.Title
	case "scores":
		return m.Scores
	case "created_at":
		return m.CreatedAt
	case "updated_at":
		return m.UpdatedAt
	default:
		return nil
	}
}

var _lorm_file_model_5b017786_Report_insert_columns = []string{
	"id",
	"title",
	"scores",
	"created_at",
	"updated_at",
}

var _lorm_file_model_5b017786_Report_insert_columns_without_auto_increment = []string{
	"title",
	"scores",
	"created_at",
	"updated_at",
}

func (m *Report) LormBeforeInsert(now lorm.HookTime) lorm.InsertPlan {
	if m.CreatedAt.IsZero() {
		m.CreatedAt = now
	}
	if m.UpdatedAt.IsZero() {
		m.UpdatedAt = now
	}

	plan := lorm.InsertPlan{}
	plan.AutoIncrementColumn = "id"
	plan.AutoIncrementZero = m.ID == 0
	if plan.AutoIncrementZero {
		plan.Columns = _lorm_file_model_5b017786_Report_insert_columns_without_auto_increment
	} else {
		plan.Columns = _lorm_file_model_5b017786_Report_insert_columns
	}
	plan.Values = make([]any, 0, len(plan.Columns))
	if !plan.AutoIncrementZero {
		plan.Values = append(plan.Values, m.ID)
	}
	plan.Values = append(plan.Values, m.Title)
	plan.Values = append(plan.Values, m.Scores)
	plan.Values = append(plan.Values, m.CreatedAt)
	plan.Values = append(plan.Values, m.UpdatedAt)
	return plan
}

func (m *Report) LormAfterInsert(result lorm.InsertResult) error {
	if !result.HasGeneratedID {
		return nil
	}
	value, err := lorm.ConvertGeneratedSignedID[int64](result.GeneratedID, 64, "Report.ID")
	if err != nil {
		return err
	}
	m.ID = value
	return nil
}

func (m *Report) LormBeforeUpdate(now lorm.HookTime) (lorm.UpdatePlan, error) {
	plan := lorm.UpdatePlan{
		Set:       make([]lorm.ColumnValue, 0, 5),
		Where:     make([]lorm.ColumnValue, 0),
		Increment: make([]string, 0, 1),
	}
	plan.PrimaryKeyCount++
	plan.Where = append(plan.Where, lorm.ColumnValue{Column: "id", Value: m.ID})
	plan.Set = append(plan.Set, lorm.ColumnValue{Column: "title", Value: m.Title})
	plan.Set = append(plan.Set, lorm.ColumnValue{Column: "scores", Value: m.Scores})
	plan.Set = append(plan.Set, lorm.ColumnValue{Column: "updated_at", Value: now})
	return plan, nil
}

func (m *Report) LormAfterUpdate(now lorm.HookTime, rowsAffected int64) {
	if rowsAffected <= 0 {
		return
	}
	{
		m.UpdatedAt = now
	}
}

var _lorm_file_model_5b017786_Report_model_descriptor = _lorm_file_model_5b017786_model_descriptor_map["Report"]

func (m *Report) LormModelDescriptor() *lorm.ModelDescriptor {
	return _lorm_file_model_5b017786_Report_model_descriptor
}

func (m *Report) Fields() *Report_Fields {
	return default_Report_Fields
}

var default_Report_Fields = new(Report_Fields)

type Report_Fields struct {
	alias string
}

func (f *Report_Fields) WithAlias(alias string) *Report_Fields {
	o := new(Report_Fields)
	o.alias = alias
	return o
}
func (f *Report_Fields) ID() string {
	if f.alias == "" {
		return "id"
	}
	return f.alias + ".id"
}
func (f *Report_Fields) Title() string {
	if f.alias == "" {
		return "title"
	}
	return f.alias + ".title"
}
func (f *Report_Fields) Scores() string {
	if f.alias == "" {
		return "scores"
	}
	return f.alias + ".scores"
}
func (f *Report_Fields) CreatedAt() string {
	if f.alias == "" {
		return "created_at"
	}
	return f.alias + ".created_at"
}
func (f *Report_Fields) UpdatedAt() string {
	if f.alias == "" {
		return "updated_at"
	}
	return f.alias + ".updated_at"
}

func (f *Report_Fields) All() []string {
	return []string{
		f.ID(),
		f.Title(),
		f.Scores(),
		f.CreatedAt(),
		f.UpdatedAt(),
	}
}

const _lorm_file_model_5b017786_raw = `{"Path":"model.go","LormImportAlias":"lorm","Package":"main","Imports":[{"Path":"\"database/sql/driver\"","Alias":""},{"Path":"\"fmt\"","Alias":""},{"Path":"\"strconv\"","Alias":""},{"Path":"\"strings\"","Alias":""},{"Path":"\"time\"","Alias":""},{"Path":"\"github.com/yvvlee/lorm\"","Alias":""}],"Structs":[{"Name":"Report","TableName":"reports","Fields":[{"Name":"ID","FullName":"ID","DBField":"id","Type":"int64","Flag":3},{"Name":"Title","FullName":"Title","DBField":"title","Type":"string","Flag":0},{"Name":"Scores","FullName":"Scores","DBField":"scores","Type":"CSVInts","Flag":0},{"Name":"CreatedAt","FullName":"CreatedAt","DBField":"created_at","Type":"time.Time","Flag":8},{"Name":"UpdatedAt","FullName":"UpdatedAt","DBField":"updated_at","Type":"time.Time","Flag":16}],"PrimaryKeys":["id"]}]}`

var _lorm_file_model_5b017786_model_descriptor_map = func() map[string]*lorm.ModelDescriptor {
	var file lorm.FileDescriptor
	_ = json.UnmarshalString(_lorm_file_model_5b017786_raw, &file)
	m := make(map[string]*lorm.ModelDescriptor, len(file.Structs))
	for _, s := range file.Structs {
		m[s.Name] = s
	}
	return m
}()
