// Code generated by Lorm. DO NOT EDIT.

package main

import (
	json "github.com/bytedance/sonic"

	"github.com/yvvlee/lorm"
)

func (m *Account) TableName() string {
	return "accounts"
}

func (m *Account) New() lorm.Model {
	return new(Account)
}

func (m *Account) LormFieldPtr(name string) any {
	switch name {
	case "id":
		return &m.ID
	case "owner":
		return &m.Owner
	case "balance":
		return &m.Balance
	default:
		return nil
	}
}

func (m *Account) LormModelDescriptor() *lorm.ModelDescriptor {
	return _lorm_file_model_model_descriptor_map["Account"]
}

func (m *Account) Fields() *Account_Fields {
	return default_Account_Fields
}

var default_Account_Fields = new(Account_Fields)

type Account_Fields struct {
	alias string
}

func (f *Account_Fields) WithAlias(alias string) *Account_Fields {
	o := new(Account_Fields)
	o.alias = alias
	return o
}
func (f *Account_Fields) ID() string {
	if f.alias == "" {
		return "id"
	}
	return f.alias + ".id"
}
func (f *Account_Fields) Owner() string {
	if f.alias == "" {
		return "owner"
	}
	return f.alias + ".owner"
}
func (f *Account_Fields) Balance() string {
	if f.alias == "" {
		return "balance"
	}
	return f.alias + ".balance"
}

func (f *Account_Fields) All() []string {
	return []string{
		f.ID(),
		f.Owner(),
		f.Balance(),
	}
}

const _lorm_file_model_raw = `{"Path":"model.go","LormImportAlias":"lorm","Package":"main","Imports":[{"Path":"\"github.com/yvvlee/lorm\"","Alias":""}],"Structs":[{"Name":"Account","TableName":"accounts","Fields":[{"Name":"ID","FullName":"ID","DBField":"id","Type":"int64","Flag":3},{"Name":"Owner","FullName":"Owner","DBField":"owner","Type":"string","Flag":0},{"Name":"Balance","FullName":"Balance","DBField":"balance","Type":"int64","Flag":0}]}]}`

var _lorm_file_model_model_descriptor_map = func() map[string]*lorm.ModelDescriptor {
	var file lorm.FileDescriptor
	_ = json.UnmarshalString(_lorm_file_model_raw, &file)
	m := make(map[string]*lorm.ModelDescriptor, len(file.Structs))
	for _, s := range file.Structs {
		m[s.Name] = s
	}
	return m
}()
