// Code generated by Lorm. DO NOT EDIT.

package main

import (
	json "github.com/bytedance/sonic"

	"github.com/yvvlee/lorm"
)

func (m *Document) TableName() string {
	return "documents"
}

func (m *Document) New() lorm.Model {
	return new(Document)
}

func (m *Document) LormFieldPtr(name string) any {
	switch name {
	case "id":
		return &m.ID
	case "title":
		return &m.Title
	case "version":
		return &m.Version
	case "updated_at":
		return &m.UpdatedAt
	default:
		return nil
	}
}

func (m *Document) LormFieldValue(name string) any {
	switch name {
	case "id":
		return m.ID
	case "title":
		return m.Title
	case "version":
		return m.Version
	case "updated_at":
		return m.UpdatedAt
	default:
		return nil
	}
}

func (m *Document) LormModelDescriptor() *lorm.ModelDescriptor {
	return _lorm_file_model_model_descriptor_map["Document"]
}

func (m *Document) Fields() *Document_Fields {
	return default_Document_Fields
}

var default_Document_Fields = new(Document_Fields)

type Document_Fields struct {
	alias string
}

func (f *Document_Fields) WithAlias(alias string) *Document_Fields {
	o := new(Document_Fields)
	o.alias = alias
	return o
}
func (f *Document_Fields) ID() string {
	if f.alias == "" {
		return "id"
	}
	return f.alias + ".id"
}
func (f *Document_Fields) Title() string {
	if f.alias == "" {
		return "title"
	}
	return f.alias + ".title"
}
func (f *Document_Fields) Version() string {
	if f.alias == "" {
		return "version"
	}
	return f.alias + ".version"
}
func (f *Document_Fields) UpdatedAt() string {
	if f.alias == "" {
		return "updated_at"
	}
	return f.alias + ".updated_at"
}

func (f *Document_Fields) All() []string {
	return []string{
		f.ID(),
		f.Title(),
		f.Version(),
		f.UpdatedAt(),
	}
}

const _lorm_file_model_raw = `{"Path":"model.go","LormImportAlias":"lorm","Package":"main","Imports":[{"Path":"\"time\"","Alias":""},{"Path":"\"github.com/yvvlee/lorm\"","Alias":""}],"Structs":[{"Name":"Document","TableName":"documents","Fields":[{"Name":"ID","FullName":"ID","DBField":"id","Type":"int64","Flag":3},{"Name":"Title","FullName":"Title","DBField":"title","Type":"string","Flag":0},{"Name":"Version","FullName":"Version","DBField":"version","Type":"int","Flag":32},{"Name":"UpdatedAt","FullName":"UpdatedAt","DBField":"updated_at","Type":"time.Time","Flag":16}]}]}`

var _lorm_file_model_model_descriptor_map = func() map[string]*lorm.ModelDescriptor {
	var file lorm.FileDescriptor
	_ = json.UnmarshalString(_lorm_file_model_raw, &file)
	m := make(map[string]*lorm.ModelDescriptor, len(file.Structs))
	for _, s := range file.Structs {
		m[s.Name] = s
	}
	return m
}()
