// Code generated by Lorm. DO NOT EDIT.

package main

import (
	json "github.com/bytedance/sonic"

	"github.com/yvvlee/lorm"
)

func (m *Role) TableName() string {
	return "roles"
}

func (m *Role) New() lorm.Model {
	return new(Role)
}

func (m *Role) LormFieldPtr(name string) any {
	switch name {
	case "id":
		return &m.ID
	case "name":
		return &m.Name
	default:
		return nil
	}
}

func (m *Role) LormModelDescriptor() *lorm.ModelDescriptor {
	return _lorm_file_model_model_descriptor_map["Role"]
}

func (m *Role) Fields() *Role_Fields {
	return default_Role_Fields
}

var default_Role_Fields = new(Role_Fields)

type Role_Fields struct {
	alias string
}

func (f *Role_Fields) WithAlias(alias string) *Role_Fields {
	o := new(Role_Fields)
	o.alias = alias
	return o
}
func (f *Role_Fields) ID() string {
	if f.alias == "" {
		return "id"
	}
	return f.alias + ".id"
}
func (f *Role_Fields) Name() string {
	if f.alias == "" {
		return "name"
	}
	return f.alias + ".name"
}

func (f *Role_Fields) All() []string {
	return []string{
		f.ID(),
		f.Name(),
	}
}

func (m *User) TableName() string {
	return "users"
}

func (m *User) New() lorm.Model {
	return new(User)
}

func (m *User) LormFieldPtr(name string) any {
	switch name {
	case "id":
		return &m.ID
	case "name":
		return &m.Name
	case "email":
		return &m.Email
	case "role_id":
		return &m.RoleID
	case "created_at":
		return &m.CreatedAt
	case "updated_at":
		return &m.UpdatedAt
	default:
		return nil
	}
}

func (m *User) LormModelDescriptor() *lorm.ModelDescriptor {
	return _lorm_file_model_model_descriptor_map["User"]
}

func (m *User) Fields() *User_Fields {
	return default_User_Fields
}

var default_User_Fields = new(User_Fields)

type User_Fields struct {
	alias string
}

func (f *User_Fields) WithAlias(alias string) *User_Fields {
	o := new(User_Fields)
	o.alias = alias
	return o
}
func (f *User_Fields) ID() string {
	if f.alias == "" {
		return "id"
	}
	return f.alias + ".id"
}
func (f *User_Fields) Name() string {
	if f.alias == "" {
		return "name"
	}
	return f.alias + ".name"
}
func (f *User_Fields) Email() string {
	if f.alias == "" {
		return "email"
	}
	return f.alias + ".email"
}
func (f *User_Fields) RoleID() string {
	if f.alias == "" {
		return "role_id"
	}
	return f.alias + ".role_id"
}
func (f *User_Fields) CreatedAt() string {
	if f.alias == "" {
		return "created_at"
	}
	return f.alias + ".created_at"
}
func (f *User_Fields) UpdatedAt() string {
	if f.alias == "" {
		return "updated_at"
	}
	return f.alias + ".updated_at"
}

func (f *User_Fields) All() []string {
	return []string{
		f.ID(),
		f.Name(),
		f.Email(),
		f.RoleID(),
		f.CreatedAt(),
		f.UpdatedAt(),
	}
}

func (m *UserWithRole) New() lorm.Model {
	return new(UserWithRole)
}

func (m *UserWithRole) LormFieldPtr(name string) any {
	switch name {
	case "user_id":
		return &m.UserID
	case "user_name":
		return &m.UserName
	case "email":
		return &m.Email
	case "role_name":
		return &m.RoleName
	default:
		return nil
	}
}

func (m *UserWithRole) LormModelDescriptor() *lorm.ModelDescriptor {
	return _lorm_file_model_model_descriptor_map["UserWithRole"]
}

func (m *UserWithRole) Fields() *UserWithRole_Fields {
	return default_UserWithRole_Fields
}

var default_UserWithRole_Fields = new(UserWithRole_Fields)

type UserWithRole_Fields struct {
	alias string
}

func (f *UserWithRole_Fields) WithAlias(alias string) *UserWithRole_Fields {
	o := new(UserWithRole_Fields)
	o.alias = alias
	return o
}
func (f *UserWithRole_Fields) UserID() string {
	if f.alias == "" {
		return "user_id"
	}
	return f.alias + ".user_id"
}
func (f *UserWithRole_Fields) UserName() string {
	if f.alias == "" {
		return "user_name"
	}
	return f.alias + ".user_name"
}
func (f *UserWithRole_Fields) Email() string {
	if f.alias == "" {
		return "email"
	}
	return f.alias + ".email"
}
func (f *UserWithRole_Fields) RoleName() string {
	if f.alias == "" {
		return "role_name"
	}
	return f.alias + ".role_name"
}

func (f *UserWithRole_Fields) All() []string {
	return []string{
		f.UserID(),
		f.UserName(),
		f.Email(),
		f.RoleName(),
	}
}

const _lorm_file_model_raw = `{"Path":"model.go","LormImportAlias":"lorm","Package":"main","Imports":[{"Path":"\"time\"","Alias":""},{"Path":"\"github.com/yvvlee/lorm\"","Alias":""}],"Structs":[{"Name":"Role","TableName":"roles","Fields":[{"Name":"ID","FullName":"ID","DBField":"id","Type":"int64","Flag":3},{"Name":"Name","FullName":"Name","DBField":"name","Type":"string","Flag":0}]},{"Name":"User","TableName":"users","Fields":[{"Name":"ID","FullName":"ID","DBField":"id","Type":"int64","Flag":3},{"Name":"Name","FullName":"Name","DBField":"name","Type":"string","Flag":0},{"Name":"Email","FullName":"Email","DBField":"email","Type":"string","Flag":0},{"Name":"RoleID","FullName":"RoleID","DBField":"role_id","Type":"int64","Flag":0},{"Name":"CreatedAt","FullName":"CreatedAt","DBField":"created_at","Type":"time.Time","Flag":8},{"Name":"UpdatedAt","FullName":"UpdatedAt","DBField":"updated_at","Type":"time.Time","Flag":16}]},{"Name":"UserWithRole","TableName":"","Fields":[{"Name":"UserID","FullName":"UserID","DBField":"user_id","Type":"int64","Flag":0},{"Name":"UserName","FullName":"UserName","DBField":"user_name","Type":"string","Flag":0},{"Name":"Email","FullName":"Email","DBField":"email","Type":"string","Flag":0},{"Name":"RoleName","FullName":"RoleName","DBField":"role_name","Type":"string","Flag":0}]}]}`

var _lorm_file_model_model_descriptor_map = func() map[string]*lorm.ModelDescriptor {
	var file lorm.FileDescriptor
	_ = json.UnmarshalString(_lorm_file_model_raw, &file)
	m := make(map[string]*lorm.ModelDescriptor, len(file.Structs))
	for _, s := range file.Structs {
		m[s.Name] = s
	}
	return m
}()
